### ISSUE TITLE
alt+click opens a new window instead of a tab

### ISSUE THREAD

**Issue by neolao** [Gert-dev/php-integrator-navigation#2] opened 2015-11-18 12:25 UTC

**Comment by Gert-dev** [comment] 2015-11-20 20:50
I can't reproduce this issue. I'm thinking this is either another package causing strange behaviour or an Atom bug (my Atom also spawns windows instead of editors in the current window sometimes, such as when opening remote files). I'm using standard functionality from the Atom workspace to request to open a file (`atom.workspace.open`), which does not offer control over whether it happens in a separate window or not.

**Comment by Gert-dev** [comment] 2015-12-02 20:11
I'm closing this as I'm assuming you got it sorted out as no further issues were reported after my initial reply. Feel free to reopen or reply if this is not the case.

**Closed by Gert-dev** 2015-12-02 20:11 UTC
