### ISSUE TITLE
Jump to $this->{method} from parent class

### ISSUE THREAD

**Issue by lukasoppermann** [Gert-dev/php-integrator-navigation#17] opened 2016-04-21 09:07 UTC
Jumping to `$this->myMethod()` works like a charm, if the method is defined in the current class. However, if the method comes from the parent class, that is extended by the current class, it does not work.

This would be a very nice improvement.

**Comment by Gert-dev** [comment] 2016-04-21 18:02
Hello. Do you have a small example where I can reproduce this? This should already be working correctly (as well as navigating to methods from traits or interfaces).

**Comment by lukasoppermann** [comment] 2016-04-22 07:39
Hey, I actually only have complicated files, but one example is like this:

I have an ApiController that extends Controller

**Controller.php**
```php
<?php

namespace App\Api\V1\Controllers;

use Laravel\Lumen\Routing\Controller as LumenController;
use Illuminate\Http\Request;
use \Dingo\Api\Routing\Helpers;

abstract class Controller extends LumenController
{
    /**
     * returns current resources transformer
     *
     * @method newTransformer
     *
     * @return transformer
     */
    public function newTransformer(){
        // get transformer namespace
        $transformer = $this->api_namespace."Transformers\\".$this->resourceName()."Transformer";
        // return a new transformer
        return new $transformer;
    }
}
```

**ApiController.php**
```php
<?php

namespace App\Api\V1\Controllers;

use Illuminate\Http\Request;
use App\Api\V1\Requests\ApiRequest;
use Illuminate\Pagination\LengthAwarePaginator;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

abstract class ApiController extends Controller
{
    /*
     * index
     */
    public function index()
    {
        // get model instance
        $model = $this->newModel();
        // apply filters
        foreach((array) $this->request->input('filter') as $key => $value){
            $model = $model->where($key, $value);
        }
        // return result
        return $this->response->paginator($model->paginate($this->perPage), $this->newTransformer(), ['key' => $this->resource]);
    }
}
```

Is the problem due to them being `abstract`?

**Comment by Gert-dev** [comment] 2016-04-23 10:21
At a first glance, your code looks fine and should also be working correctly. Is it the `$this->newTransformer()` method call that is not working on alt-click in the `index` method? Is the method itself underlined with a full line or a dashed line?

**Comment by lukasoppermann** [comment] 2016-04-23 10:36
Yes, the `$this->newTransformer()` is not working on alt-click and it does show a **dashed** line. Does that help?

**Comment by Gert-dev** [comment] 2016-04-23 18:34
That means that it is actually indeed not recognizing the method as being one of its own (that or the type of `$this` is not being correctly determined, but I doubt that is the case as the code is correct and I can get a similar expression working locally).

Could you, out of curiosity, try making a single change in the parent class file and then trying again? If that doesn't work, does a force reindex help? If it works, it means there were some changes (perhaps a file name or namespace changed) that the indexer didn't pick up yet or somehow missed. If it doesn't, it is a consistent problem and there is something else wrong.

**Comment by lukasoppermann** [comment] 2016-04-24 06:28
Hey,

so if I do the following it works:

```php
$transfomer = $this->newTransformer();
```

Also the sidebar from https://atom.io/packages/php-integrator-symbol-viewer (with include inherited turned on) always works fine.

However this never works. **Reindexing** does not help and a **Force Reindex** produces an error (see below).

```php
return $this->response->paginator(
   $model->paginate($this->perPage), 
   $this->newTransformer(), 
   ['key' => $this->resource]
);
```

Can you also tell me how I get rid of this error again?

**The Error:**

> PHP sent back something unexpected. This is most likely an issue with your setup. If you're sure this is a bug, feel free to report it on the bug tracker.
>  
> → A driver exception occurred. Please check if support for sqlite is present.
>  
> /Users/lukasoppermann/.atom/packages/php-integrator-base/php/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:85 - An exception occurred while executing 'PRAGMA user_version':
> SQLSTATE[HY000]: General error: 10 disk I/O error

**Comment by Gert-dev** [comment] 2016-04-24 10:27
Thanks for the compliment!

The general error is something that SQLite seems to output when "something went wrong with I/O" without further providing any information as to what exactly went wrong. This could be a myriad of things. You can try removing the database file from the ~/.atom/packages/php-integrator-base/indexes folder manually (you can find out which one it is by putting a breakpoint in Main.coffee of the base package in `performDirectoriesIndex`, which just does an md5 hash of the project folders).

I've tried a couple of other things but I can get the code working properly here for navigation (including the two example file you provided), which seems to rule out parsing errors in the PHP or CoffeeScript code. The indexing also seems to be happening correctly as you can actually see the members in the symbol viewer (and navigating works in another context).

(I was trying to avoid this up until now, but) I think the only way to get to the bottom of this is debugging it manually via the code. I'll try to guide you through the steps, hopefully the output of some of the methods will provide a clue as to why it's not picking it up correctly:

1. Open up the developer tools (Ctrl+Shift+I or perhaps Cmd+Shift+I on Mac keyboards).
2. Go to the *Sources* tab, press Ctrl+P (or Cmd+P?) to search for files and search for `MethodProvider.coffee`. There may be multiple, be sure to select the one from the navigation package and the one with the shortest name (there are usually two for each file, one CoffeeScript variant with the original code and one compiled version in JavaScript form).
3. Put a breakpoint on line 46 (the `getResultingTypeAt` call).
4. To trigger the breakpoint, simply hover over the `newTransformer` method that is showing the dashed line, the breakpoint should now trigger.
5. I suspect the output of this method will be null, but you can verify that by stepping over the line in the debugger and looking at what is in the local `className` variable.
6. If the output is indeed null, try triggering the breakpoint again and stepping into the `getResultingTypeAt` call. It will now jump to another file in the base package, try walking over the `callStack = ...` line and seeing what is returned as call stack. This should be something like `callStack = ["$this", "newTrans"]`

Apart from this, can you think of any other "non-standard" circumstances you're in, such as:
* Using a different encoding than UTF-8.
* Using a different line ending than UNIX line endings. (Shouldn't cause any problems but you never know.)
* ...

**Comment by lukasoppermann** [comment] 2016-05-02 14:35
Hey @Gert-dev,

I tried to follow your instructions but don't understand:

> If the output is indeed null, try triggering the breakpoint again and stepping into the getResultingTypeAt call. It will now jump to another file in the base package, try walking over the callStack = ... line and seeing what is returned as call stack. This should be something like callStack = ["$this", "newTrans"]

Before it actually shows `undefined`.

<img width="182" alt="screen shot 2016-05-02 at 16 30 40" src="https://cloud.githubusercontent.com/assets/813754/14957093/adc3a3d8-1083-11e6-9402-34c17c9e3c2d.png">

> Apart from this, can you think of any other "non-standard" circumstances you're in, such as:
No, nothing that I could think of.

I mean it is an abstract class extending an abstract class. I am not sure if this is unusual or something.

**Comment by Gert-dev** [comment] 2016-05-02 15:35
Did you try stepping over the line itself (F10 while the breakpoint is triggered, i.e. moving to the `getClassMethod` call on the next line)?

You can also step into the method by using F11 whilst the breakpoint is on the `getResultingTypeAt` call and then take it from there by stepping over again to see what is going on.

**Comment by lukasoppermann** [comment] 2016-05-02 16:09
Okay, I get this, does this make sense?

<img width="876" alt="screen shot 2016-05-02 at 18 07 50" src="https://cloud.githubusercontent.com/assets/813754/14959715/ee2025ac-1090-11e6-8bed-3febf761f03e.png">

<img width="1398" alt="screen shot 2016-05-02 at 18 08 41" src="https://cloud.githubusercontent.com/assets/813754/14959720/f1f0e7e8-1090-11e6-9785-21ff0032a952.png">

**Comment by Gert-dev** [comment] 2016-05-02 17:00
Ok, that confirms what I thought and should allow you to do step 6: get a breakpoint to trigger on the `getResultingTypeAt` call and use `Step into` (F11) to go inside it, this should take you to the method definition in the base package. You can then try stepping over the lines to examine the content of the local variables. `callStack` is one of those variables.

**Comment by lukasoppermann** [comment] 2016-05-02 17:21
I get to this. How to I `stepping over the lines`? I have no idea of breakpoints, sorry, never used them.

<img width="1440" alt="screen shot 2016-05-02 at 19 17 09" src="https://cloud.githubusercontent.com/assets/813754/14961565/842f1bbc-109a-11e6-9c54-a5042feac0be.png">

**Comment by Gert-dev** [comment] 2016-05-02 17:45
So far so good, from here you can click the button next to the "Play/Pause button" in the right panel, which is the "Step over" button. You can also trigger it with F11.

**Comment by lukasoppermann** [comment] 2016-05-02 17:49
Okay, so I hovered this:
<img width="530" alt="screen shot 2016-05-02 at 19 47 49" src="https://cloud.githubusercontent.com/assets/813754/14962385/d6a64524-109e-11e6-995c-c23bf99175b8.png">

And got this:

<img width="1120" alt="screen shot 2016-05-02 at 19 47 33" src="https://cloud.githubusercontent.com/assets/813754/14962406/e6160f8a-109e-11e6-8313-1b764f5ac678.png">

<img width="1084" alt="screen shot 2016-05-02 at 19 47 44" src="https://cloud.githubusercontent.com/assets/813754/14962415/ed87df28-109e-11e6-827c-9554ab223231.png">

It seems to not pick up the "Trashed" part of "withTrashed".

**Comment by Gert-dev** [comment] 2016-05-02 17:56
Ah, I thought you were still trying to debug the `$this->newTransformer` call. The last word only being partially picked up is correct: it is popped off later and not relevant here (as the type being sought after is actually the type of `$model` here). Is `$model` assigned to `$this` before the code from the screenshot?

**Comment by lukasoppermann** [comment] 2016-05-02 17:57
Ahh, sorry, I thought it is the same for all, let me try this with `$this->newTransformer`.

**Comment by Gert-dev** [comment] 2016-05-02 19:11
Regarding `newModel`: That's strange, are you sure the mouse was exactly on `newModel` when the breakpoint triggered? Normally it should only trigger for actual members (and not strings). I can't locally get a breakpoint to trigger inside the string, but it could be there is something wrong with the fetching of the element based on the mouse coordinates.

Regarding `$model->withTrashed`: what is `$model` assigned to?

**Comment by lukasoppermann** [comment] 2016-05-03 06:05
Well, actually `$model` is assigned to `$this->newModel()` which returns an instance of a new model class.

What is very weird is that I found that in the same file, some of the `$this->newModel()` instances trigger correctly and others have the dashed line. And they both are within the same code piece that I showed above.

Regarding your first question. I re-checked and it definitely triggered when the mouse was over the `newModel` with the dashed line.

**Comment by Gert-dev** [comment] 2016-05-03 16:01
Does `newModel` have a docblock that returns the correct type? I realize you've already shown me some of your code, but is it possible you could upload it to a git repo in its entirety? That is, if it is not part of a proprietary code base. That way I can verify whether it is some kind of setup problem or a general issue. If you're not (entirely) comfortable with this, no problem.

**Comment by lukasoppermann** [comment] 2016-05-04 07:15
Hey, sorry, I can not upload all the code, especially since it will be many files.

However I am pretty sure the docblock type is not correct. It is a dynamic function so I don't know which model it returns (it depends on where it is called). But do you have any idea why it works sometimes and sometimes not, for `newModel` in the same file, in the same code block? 

Is there a guide on how docblocks should be formatted for the package to pick it up correctly?

```php
/**
     * returns current resources model
     *
     * @method newModel
     *
     * @return Illuminate\Database\Eloquent\Model
     */
    public function newModel($model = NULL){
        // use controller model if none provided
        if($model === NULL){
            $model = $this->resourceName();
        }
        // get model namespace
        $model = $this->api_namespace."Models\\".$model;
        // return a new mode
        return new $model;
    }
```

**Comment by Gert-dev** [comment] 2016-05-04 16:40
The docblock issue makes sense, but it is strange that code navigation only works in some places for the same expression. The "expression" that you're trying to click is first parsed in CoffeeScript and afterwards the PHP side tries to resolve the type (this is because the PHP parser used can't currently cope with partial expressions), so my first idea would be that the non-working expression is not getting parsed correctly (i.e. something like `'my_string' . $this->foo()` is being retrieved instead of just `$this->foo()`), but that should have shown up in the call stack you already debugged above.

If the call stack is not the problem, it must be due to the PHP side not being able to resolve the type properly. To find out if this is the case, we'll need to move to debugging the PHP side instead. It is the `DeduceType` command that determines the type of the expression, so in theory the `deduceType` method in `php-integrator-base/php/src/Application/Command/DeduceType.php` should be returning null or something else incorrect when you hover that expression. If you put a `die(var_dump('test'));` somewhere in this method, Atom should start popping up error notifications whenever it tries to resolve the type and it fails because of the die statement. You can use this to find out what exactly is being passed in (`$expressionParts`) and what is going out (the return statements).

Finally, regarding how docblocks should be formatted: I try to follow the PSR-5 standard [1] (which is mostly based on phpDocumentor [2]). If you're also using the linter package, it should underline invalid types in the docblock as well. But in essence, the types used in docblocks follow the same rules as types used in the PHP code (i.e. they are relative to use statements or need to be fully qualified).

[1] https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md
[2] https://phpdoc.org/docs/latest/index.html

**Comment by Gert-dev** [comment] 2016-07-05 17:09
I'll close this due to the age of my last comment. Feel free to respond or create a new ticket if this issue is still present.

**Closed by Gert-dev** 2016-07-05 17:09 UTC
